# Generated by Django 2.1.5 on 2020-09-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200903_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body_context',
            new_name='body_content',
        ),
    ]
