# Generated by Django 2.1.5 on 2020-09-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200903_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply_str',
            new_name='reply_to',
        ),
    ]
